# Specification for /product/{id}
parameters:
  - $ref: "../parameters/productId.yaml"

put:
  tags:
    - Товары
  summary: Добавить новый товар
  description: Добавляет товар в базу данных c указанным идентификатором.
  operationId: addProduct
  security:
    - OTPSchema: []

  requestBody:
    description: Creating new product
    required: true
    content:
      "application/json":
        schema:
          $ref: ../schemas/product.partial.yaml
  responses:
    201:
      description: A product to be returned
      content:
        application/json:
          schema:
            $ref: "../schemas/product.yaml"

    401:
      $ref: ../responses/_index.yaml#/401
    403:
      $ref: ../responses/_index.yaml#/403

patch:
  tags:
    - Товары
  summary: Обновить данные о товаре
  description: Обновляет информацию о товаре
  operationId: patchProduct
  security:
    - OTPSchema: []

  requestBody:
    description: Updating product
    required: true
    content:
      "application/json":
        schema:
          $ref: ../schemas/product.base.yaml
        example:
          $ref: ../examples/product.patch.yaml
  responses:
    200:
      description: A product to be returned
      content:
        application/json:
          schema:
            $ref: "../schemas/product.yaml"

    401:
      $ref: ../responses/_index.yaml#/401
    403:
      $ref: ../responses/_index.yaml#/403

get:
  tags:
    - Товары
  summary: Подробно о товаре
  description: Позволяет получить подробную информацию об одном товаре.
  operationId: getProduct
  security: []

  responses:
    200:
      description: A product to be found
      content:
        application/json:
          schema:
            $ref: "../schemas/product.yaml"
    404:
      $ref: ../responses/_index.yaml#/404
