# Specification for /product
get:
    tags: 
        -  Товары
    parameters: 
      - $ref: ../parameters/fields.yaml
      - $ref: ../parameters/limit.yaml
      - $ref: ../parameters/offset.yaml
      - $ref: ../parameters/sort.yaml
      - $ref: ../parameters/order.yaml

        
    summary: Список товаров
    description: Получить список товаров
    operationId: getProducts
    security: []

    responses:
        "200":
            description: List of products
            headers:
                $ref: ../schemas/pagination.yaml
                
            content:
                application/json:
                    schema:
                        $ref: "../schemas/products.yaml"
                    example: 
                        $ref: ../examples/products.yaml
        "404":
            description: Can't find anything
            content:
                application/json:
                    schema:
                        $ref: '../schemas/error.yaml'