# Schema for Product object
type: object
properties:
  eid:
    type: string
    description: Уникальный идентификатор товара в системе поставщика.
    example: "UT-00025383"
  sku:
    type: string
    description: Артикул товара
    example: A78563S
  stock:
    type: integer
    description: Количество товара на складе доступное для заказа.
    example: 18
    default: 0
  weight:
    type: number
    description: Вес товара для службы доставки
    example: 32.023
  title:
    type: string
    description: Наименование товара.
    example: 'Растворитель для переходов в банке ОНБ "МАГИЯ МЕРЛИНА" 500 мл'
  price:
    type: number
    description: Базовая стоимость товара.
    example: 779.00
  oldPrice:
    type: number
    nullable: true
    description: Старая цена.
    example: 820.00
    default: null
  prices:
    type: array
    nullable: true
    description: Вилка цен
    items:
      type: object
      properties:
        qnty:
          type: number
          description: Количество товара от которого действует цена
          example: 3
        price:
          type: number
          description: Цена при достижении количества товара в корзине
          example: 750
  rate:
    type: number
    description: Значимость товара для продавца. Может использоваться для сортировки.
    example: 200
  category:
    type: string
    description: Категория товара
    example: Растворители
  brand:
    type: string
    description: Бренд
    example: ОНБ
  shortDescription:
    type: string
    description: Обыкновенный растворитель.
  longDescription:
    type: string
    description: Если вам надо что-то растворить, то...
  position:
    type: string
    enum: [topList, ""]
    description: Идентификатор блока для отображения  товара.
    example: topList
  specification:
    type: object
    description: Набор характеристик товара с соответствующими значениями.
    example:
      "Цвет": "Желтый"
      "Объем": "1л"
  badge:
    type: object
    nullable: true
    properties:
      type:
        type: string
      value:
        type: string
    example:
      type: discount
      value: 5%
  isArchived:
    type: boolean
    description: Флаг для архивных продуктов, которых не должно быть в каталоге
    default: false
  related_products:
    type: array
    items:
      type: string
    default: []
    example:
      - 62bc4176c1f085001c826a80
      - 62bc5ed5381cb0001caa1b90
      - 60df05aead83db001cd2993a
