# Schema for Product object
type: object
required:
    - title
    - eid
    - price
properties:
    eid:
        type: string
        description: Уникальный идентификатор товара в системе поставщика.
        example: "a0229858-ace1-4ed0-b239-1da1b88b1bec"
    title:
        type: string
        description: Наименование товара.
        example: 'Растворитель для переходов в банке ОНБ "МАГИЯ МЕРЛИНА" 500 мл'
    price:
        type: number
        description: Стоимость товара.
        example: 779.00
    oldPrice:
        type: number
        description: Старая цена.
        example: 820.00
        default: null
    weight:
        type: number
        description: Значимость товара для продавца. Используется для сортировки.
        example: 200
    category:
        type: string
        description: Категория товара
        example: Растворители
    brand:
        type: string
        description: Бренд
        example: ОНБ
    shortDescription:
        type: string
        description: Обыкновенный растворитель.
    longDescription:
        type: string
        description: Если вам надо что-то растворить, то...
    position:
        type: string
        enum: [topList, ""]
        description: Идентификатор блока для отображения  товара.
        example: topList
    specification:
        type: object
        description: Набор характеристик товара с соответствующими значениями.
        example: 
            "Цвет": "Желтый"
            "Объем": "1л"
    badge:
        type: object
        properties: 
            type: 
                type: string
                enum: [discount,new]
            value:
                type: string
        example: 
            type: discount
            value: 5%

