# Schema for Product object
allOf: 
  - type: object
    properties:
        id:
            type: string
            description: Уникальный идентификатор товара. Генерируется сервером при создании товара.
            example: "9b944cf4-0337-43f2-a1ae-4446452e48fc"
        stock:
            type: integer
            description: Количество товара на складе доступное для заказа.
            example: 18
            readOnly: true
        createdAt:
            type: string
            format: timestamp
            description: Время добавления товара в корзину.
            example: 2023-06-09T03:19:56.186Z
        thumbnail:
            type: string
            description: Ссылка на главное изображение товара.
            example: https://onbexpress.ru/assets/products/87sfd87g6sg9sfd.webp
        images:
            type: array
            description: Массив с дополнительными изображениями товара.
            items:
                type: string
            example: 
                - https://onbexpress.ru/assets/products/87sfd87g6sg9sfd-2.webp
                - https://onbexpress.ru/assets/products/87sfd87g6sg9sfd-3.webp
  - $ref: product.partial.yaml